name: 'PHP8.3 Linter'
description: 'Run Lint whit php8.3'
author: 'Michael Wright <php-lint@wserver.co.uk>'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'eye'  
  color: 'gray-dark'
